export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_DISC = 'SET_DISC'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_CUR_INDEX = 'SET_CUR_INDEX'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_CUR_DURATION = 'SET_CUR_DURATION'
export const SET_CUR_SONG_LYRIC = 'SET_CUR_SONG_LYRIC'
export const SET_SINGER = 'SET_SINGER'
export const SET_RANK = 'SET_RANK'

// search
export const SET_QUERY = 'SET_QUERY'
export const SET_HOTS = 'SET_HOTS'
export const SET_SUGGESTS = 'SET_SUGGESTS'
export const SET_HISTORIES = 'SET_HISTORIES'
export const SET_RESULTS = 'SET_RESULTS'
export const CLEAR_HISTORIES = 'CLEAR_HISTORIES'
